### ISSUE TITLE
Issue with too big arraybuffer not succesully going through

### ISSUE THREAD

**Issue by Noitidart** [Soren-Nordstrom/userscript#3]
I use a similiar technique to you to put Blob to nsIArrayBufferInputStream here: https://github.com/Soren-Nordstrom/userscript/blob/264391f2597910b72fd1e9ec1cddfe3e457f30c8/monolith/51/130510.user.js#L3760

What I use it for is, canvas.toBlob then I postData to a new tab. If I select too big a region data is corrupted please see my topic here - https://discourse.mozilla-community.org/t/post-arraybuffer-to-loadonetab/6224

Do you know how I can fix this?

Thanks so much

**Comment by Soren-Nordstrom** [comment]
No, I didn't actually write any of the code in these scripts.  I recommend contacting the author if there's one in the script itself.

**Comment by Noitidart** [comment]
Ok thank you :)
